version: "2"
services:
### PHP + Apache2 ##########################################
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${PHP_CONTAINER_NAME}  
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${DATA_LOG_PATH}/apache2:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      - ${APACHE_CONF}/apache2.conf:/etc/apache2/apache2.conf
      - ./crontabs:/var/spool/cron/crontabs
      - ./php/supervisor:/etc/supervisor/conf.d
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      # - "${APACHE_HOST_HTTPS_PORT}:443"
      # - "${SUPERVISORD_PORT}:9001"
    networks:
      - leodock_backend

networks:
  leodock_backend:
    external: true